# -*- mode: python -*-
#
#    Copyright (C) 2016 Carl Hetherington <cth@carlh.net>
#
#    This file is part of libcxml.
#
#    libcxml is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    libcxml is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with libcxml.  If not, see <http://www.gnu.org/licenses/>.
#

def configure(conf):
    conf.env.prepend_value('LINKFLAGS', '-Lsrc')

def build(bld):
    obj = bld(features='cxx cxxprogram')
    obj.name   = 'tests'
    obj.uselib = 'BOOST_TEST BOOST_FILESYSTEM LIBXML++ LOCKED_SSTREAM'
    obj.use    = 'libcxml'
    obj.source = 'tests.cc'
    obj.target = 'tests'
    obj.install_path = ''
