def configure(conf):
    conf.check_cxx(fragment = """
                              #define BOOST_TEST_MODULE Config test\n
    			      #include <boost/test/unit_test.hpp>\n
                              int main() {}
                              """,
                              msg = 'Checking for boost unit testing library',
                              lib = ['boost_unit_test_framework', 'boost_system'],
                              uselib_store = 'BOOST_TEST')

    conf.env.prepend_value('LINKFLAGS', '-Lsrc')

def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.name   = 'tests'
    obj.uselib = 'BOOST_TEST BOOST_FILESYSTEM'
    obj.use    = 'libcxml'
    obj.source = 'tests.cc'
    obj.target = 'tests'
    obj.install_path = ''
