def configure(conf):
    conf.env.prepend_value('LINKFLAGS', '-Lsrc')

def build(bld):
    obj = bld(features='cxx cxxprogram')
    obj.name   = 'tests'
    obj.uselib = 'BOOST_TEST BOOST_FILESYSTEM LIBXML++'
    obj.use    = 'libcxml'
    obj.source = 'tests.cc'
    obj.target = 'tests'
    obj.install_path = ''
