# -*- mode: python -*-
#
#    Copyright (C) 2016 Carl Hetherington <cth@carlh.net>
#
#    This file is part of libcxml.
#
#    libcxml is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    libcxml is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with libcxml.  If not, see <http://www.gnu.org/licenses/>.
#

def build(bld):
    if bld.env.STATIC:
        obj = bld(features='cxx cxxstlib')
    else:
        obj = bld(features='cxx cxxshlib')
    obj.name = 'libcxml'
    obj.vnum = bld.env.API_VERSION
    obj.target = 'cxml'
    obj.export_includes = ['.']
    obj.uselib = 'LIBXML++ BOOST_FILESYSTEM'
    obj.source = "cxml.cc"

    bld.install_files('${PREFIX}/include/libcxml', "cxml.h")
    if bld.env.STATIC:
        bld.install_files('${PREFIX}/lib', 'libcxml.a')
