def build(bld):
    if bld.env.STATIC:
        obj = bld(features='cxx cxxstlib')
    else:
        obj = bld(features='cxx cxxshlib')
    obj.name = 'libcxml'
    obj.target = 'cxml'
    obj.export_includes = ['.']
    obj.uselib = 'LIBXML++ BOOST_FILESYSTEM'
    obj.source = "cxml.cc"

    bld.install_files('${PREFIX}/include/libcxml', "cxml.h")
    if bld.env.STATIC:
        bld.install_files('${PREFIX}/lib', 'libcxml.a')

